[package]
name = "ansible-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ansible-core = { path = "../ansible-core" }
tower-lsp = "0.20"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
serde_json = "1.0.151"

[dev-dependencies]
ansible-core = { path = "../ansible-core", features = ["test-fixtures"] }
